[package]
name = "okolors"
version = "0.1.0"
authors = ["Ivordir <Ivordir@pm.me>"]
edition = "2021"
description = "Generates a color palette for an image by performing k-means clustering in the Oklab color space."
homepage = "https://github.com/Ivordir/okcolors"
repository = "https://github.com/Ivordir/okcolors"
license = "MIT"
keywords = ["palette", "theme", "color", "oklab", "kmeans"]
categories = ["multimedia::images"]

[dependencies]
palette = "0.7.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
soa_derive = "0.12.0"

[dev-dependencies]
image = "0.24.6"
palette = "0.7.1"
