name: Test

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '42 12 * * *'

concurrency:
  group: ${{ github.workflow }}-scheduled-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  latest:
    name: With latest dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90.0
      - uses: taiki-e/install-action@6a1bd70eaac3c8bdf093356838d7ee09fda951cf # v2.85.5
        with:
          tool: cargo-hack@0.6.39
      - run: cargo update
      - run: cargo test --locked --all-features --doc
      - run: cargo hack -p okolors --locked --rust-version --feature-powerset --skip default test --lib
      - run: cargo hack -p okolors-cli --locked --rust-version --feature-powerset --skip default test
        env:
          RUSTFLAGS: -D deprecated
