name: Test

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  locked:
    name: With locked dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90.0
      - uses: taiki-e/install-action@1d76762916ba18e4f0c3b2f71fee3da83a279745 # v2.62.41
        with:
          tool: cargo-hack@0.6.45
      - run: cargo test --locked --all-features --doc
      - run: cargo hack -p okolors --locked --rust-version --feature-powerset --skip default test --lib
      - run: cargo hack -p okolors-cli --locked --rust-version --feature-powerset --skip default test

  minimal:
    name: With minimal dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@9a1d20035bdbcbc899baabe1e402e85bc33639bc # 1.90.0
      - uses: dtolnay/rust-toolchain@6d653acede28d24f02e3cd41383119e8b1b35921 # master
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@1d76762916ba18e4f0c3b2f71fee3da83a279745 # v2.62.41
        with:
          tool: cargo-hack@0.6.45
      - run: rustup default 1.90
      - run: cargo hack --remove-dev-deps
      - run: rustup run nightly cargo update -Z minimal-versions
      - run: cargo test --locked --all-features --doc
      - run: cargo hack -p okolors --locked --rust-version --feature-powerset --skip default test --lib
      - run: cargo hack -p okolors-cli --locked --rust-version --feature-powerset --skip default test
